//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prueba_tecnica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int idUsuario { get; set; }
        public string nomUsuario { get; set; }
        public string apeUsuario { get; set; }
        public string correo { get; set; }
        public int idrol { get; set; }
        public int idMembresia { get; set; }
    
        public virtual Membresia Membresia { get; set; }
        public virtual Role Role { get; set; }
    }
}
